engines:
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  nodesecurity:
    enabled: false
  eslint:
    enabled: true
    channel: "eslint-4"
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 150
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.md"
exclude_paths:
- "public/images/"
- "public/bootstrap/"
- "public/jquery/"
